"""
Django settings for kahootapp project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""


import os
from pathlib import Path

# Cesty k projektu:
# - PROJECT_DIR: adresář se složkou `kahootapp/settings/`
# - BASE_DIR: kořen repozitáře (tam je manage.py, README atd.)
PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)

# Jednoduché načtení .env souboru z kořene projektu.
# Lze v něm přepsat např. přístupy do DB nebo MS OAuth bez úprav kódu.
env_path = Path(BASE_DIR) / ".env"
if env_path.exists():
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))

# Základní nastavení stránek a přesměrování po loginu/logoutu.
SITE_ID = 1
LOGIN_REDIRECT_URL = "/"   
LOGOUT_REDIRECT_URL = "/"  

# Autentizační backendy – klasický Django + allauth (účty a sociální login).
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Nastavení allauth – přihlášení jménem i e‑mailem, bez povinného ověření e‑mailu.
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_USERNAME_REQUIRED = True

# Microsoft provider pro OAuth login. Hodnoty se berou z env proměnných.
SOCIALACCOUNT_PROVIDERS = {
    "microsoft": {
        "APP": {
            "client_id": os.environ.get("MS_CLIENT_ID", ""),
            "secret": os.environ.get("MS_CLIENT_SECRET","") ,
            "key": "",
        },
        "tenant": os.environ.get("MS_TENANT_ID", "common"),
        "AUTH_PARAMS": {
            "scope": os.environ.get("MS_AUTH_SCOPE", "User.Read"),
        },
    }
}



# Hlavní aplikace projektu a závislosti (Django, Wagtail, allauth, atd.).
INSTALLED_APPS = [
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.microsoft",
    "quiz",
    "home",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
]

# Middleware vrstvy – standardní Django + redirect middleware z Wagtailu.
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]
# Kořenová konfigurace URL pro tento projekt.
ROOT_URLCONF = "kahootapp.urls"

# Nastavení šablon – Django template backend + globální složka `kahootapp/templates`.
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(PROJECT_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kahootapp.wsgi.application"

# Databáze:
# - v Dockeru běží PostgreSQL (přes env proměnné),
# - pro lokální vývoj bez Dockeru se použije fallback na SQLite.
db_name = os.environ.get("DB_NAME")
if db_name:
    DATABASES = {
        "default": {
            "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.postgresql"),
            "NAME": db_name,
            "USER": os.environ.get("DB_USER", ""),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    # Fallback na SQLite pokud nejsou nastavené env proměnné
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }

# Výchozí validační pravidla pro hesla uživatelů.
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "cs-cz"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Hledání statických souborů – systémová složka + složky jednotlivých app.
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

    # Statika:
    # - STATICFILES_DIRS: zdrojové statické soubory pro collectstatic,
    # - STATIC_ROOT: cílová složka po collectstatic (použitá v produkci).
STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

# Média nahraná uživateli (obrázky otázek, diagram modelů, ...).
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Backend pro ukládání souborů – lokální filesystem (žádné S3 apod.).
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000

# Základní nastavení Wagtailu (název, fulltextové vyhledávání, URL admina).
WAGTAIL_SITE_NAME = "QuizIT!"

# Wagtail search backend - používáme jednoduchý database backend
# (ne postgres backend, který má problémy s indexováním dokumentů)
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
        "ATOMIC_REBUILD": True,
    }
}

WAGTAILADMIN_BASE_URL = "http://example.com"

# Povolené přípony dokumentů pro Wagtail dokumenty (včetně video formátů).
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip', 'mp4', 'webm', 'ogg', 'avi', 'mov', 'mkv']

# Fix pro django_tasks - zakázat enqueue_on_commit kvůli nekompatibilitě s Wagtail.
# Vše běží synchronně v rámci requestu, což je pro tento školní projekt v pohodě.
TASKS = {
    "default": {
        "BACKEND": "django_tasks.backends.immediate.ImmediateBackend",
    }
}
