# Generated by Django 4.2.24 on 2025-09-06 12:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('quiz', '0002_studentanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('question', 1)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('text', 0), ('answer_a', 0), ('answer_b', 0), ('answer_c', 0), ('answer_d', 0)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
