# Generated by Django 4.2.24 on 2025-10-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='join_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
