# Generated by Django 4.2.26 on 2025-11-20 18:50

from django.db import migrations, models
import secrets
import hashlib
from django.conf import settings
from django.utils import timezone


def generate_session_hash():
    random_token = secrets.token_urlsafe(32)
    secret_key = getattr(settings, 'SECRET_KEY', 'default-secret-key')
    combined = f"{random_token}{secret_key}{timezone.now().isoformat()}"
    return hashlib.sha256(combined.encode()).hexdigest()[:64]


def populate_hash_values(apps, schema_editor):
    QuizSession = apps.get_model('quiz', 'QuizSession')
    for session in QuizSession.objects.all():
        if not session.hash:
            session.hash = generate_session_hash()
            session.save(update_fields=['hash'])


def create_unique_index_if_not_exists(apps, schema_editor):
    """Vytvoří unique index pouze pokud neexistuje"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Zkontrolovat, jestli index už existuje
        cursor.execute("""
            SELECT 1 FROM pg_indexes 
            WHERE tablename = 'quiz_quizsession' 
            AND indexname = 'quiz_quizsession_hash_key'
        """)
        if not cursor.fetchone():
            # Vytvořit unique index
            cursor.execute("""
                CREATE UNIQUE INDEX quiz_quizsession_hash_key 
                ON quiz_quizsession (hash)
                WHERE hash IS NOT NULL
            """)


def drop_unique_index_if_exists(apps, schema_editor):
    """Smaže unique index pokud existuje"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP INDEX IF EXISTS quiz_quizsession_hash_key")


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_participant_questionrun_response_quizsession_and_more'),
    ]

    operations = [
        # Přidat sloupec hash bez indexu (index přidáme ručně)
        migrations.AddField(
            model_name='quizsession',
            name='hash',
            field=models.CharField(blank=True, db_index=False, max_length=64, null=True),
        ),
        # Vyplnit existující záznamy
        migrations.RunPython(populate_hash_values, migrations.RunPython.noop),
        # Přidat unique index ručně
        migrations.RunPython(create_unique_index_if_not_exists, drop_unique_index_if_exists),
        # Aktualizovat model, aby Django vědělo o unique constraintu
        migrations.AlterField(
            model_name='quizsession',
            name='hash',
            field=models.CharField(blank=True, db_index=False, max_length=64, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='QuizPage',
        ),
    ]
