# Generated by Django 4.2.26 on 2025-11-20 18:50

from django.db import migrations, models
import secrets
import hashlib
from django.conf import settings
from django.utils import timezone


def generate_session_hash():
    random_token = secrets.token_urlsafe(32)
    secret_key = getattr(settings, 'SECRET_KEY', 'default-secret-key')
    combined = f"{random_token}{secret_key}{timezone.now().isoformat()}"
    return hashlib.sha256(combined.encode()).hexdigest()[:64]


def populate_hash_values(apps, schema_editor):
    QuizSession = apps.get_model('quiz', 'QuizSession')
    for session in QuizSession.objects.all():
        if not session.hash:
            session.hash = generate_session_hash()
            session.save(update_fields=['hash'])


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_participant_questionrun_response_quizsession_and_more'),
    ]

    operations = [
        # Přidat sloupec hash bez unique constraintu
        migrations.AddField(
            model_name='quizsession',
            name='hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        # Vyplnit existující záznamy
        migrations.RunPython(populate_hash_values, migrations.RunPython.noop),
        # Přidat unique constraint
        migrations.AlterField(
            model_name='quizsession',
            name='hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
        migrations.DeleteModel(
            name='QuizPage',
        ),
    ]
