# Generated by Django 6.0 on 2026-01-04 15:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_add_jokers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id'], 'verbose_name': 'Odpověď', 'verbose_name_plural': 'Odpovědi'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['joined_at'], 'verbose_name': 'Účastník', 'verbose_name_plural': 'Účastníci'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Otázka', 'verbose_name_plural': 'Otázky'},
        ),
        migrations.AlterModelOptions(
            name='questionrun',
            options={'ordering': ['order'], 'verbose_name': 'Běh otázky', 'verbose_name_plural': 'Běhy otázek'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-id'], 'verbose_name': 'Kvíz', 'verbose_name_plural': 'Kvízy'},
        ),
        migrations.AlterModelOptions(
            name='quizsession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Sezení kvízu', 'verbose_name_plural': 'Sezení kvízů'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['answered_at'], 'verbose_name': 'Odpověď', 'verbose_name_plural': 'Odpovědi'},
        ),
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'verbose_name': 'Odpověď studenta', 'verbose_name_plural': 'Odpovědi studentů'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Správná odpověď'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question', verbose_name='Otázka'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Text odpovědi'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='display_name',
            field=models.CharField(max_length=80, verbose_name='Zobrazované jméno'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Připojil se'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='jokers_used',
            field=models.PositiveIntegerField(default=0, help_text='Počet použitých žolíků (max podle kvízu)', verbose_name='Použité žolíky'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='quiz.quizsession', verbose_name='Sezení'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel'),
        ),
        migrations.AlterField(
            model_name='question',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=20, help_text='Čas na odpověď v sekundách (5-300)', verbose_name='Čas na odpověď (s)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Obrázek otázky'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='Kvíz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Text otázky'),
        ),
        migrations.AlterField(
            model_name='questionrun',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=20, verbose_name='Délka (s)'),
        ),
        migrations.AlterField(
            model_name='questionrun',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Konec'),
        ),
        migrations.AlterField(
            model_name='questionrun',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Pořadí'),
        ),
        migrations.AlterField(
            model_name='questionrun',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Otázka'),
        ),
        migrations.AlterField(
            model_name='questionrun',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_runs', to='quiz.quizsession', verbose_name='Sezení'),
        ),
        migrations.AlterField(
            model_name='questionrun',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Začátek'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='join_code',
            field=models.CharField(blank=True, max_length=8, unique=True, verbose_name='Kód pro připojení'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='jokers_count',
            field=models.PositiveIntegerField(default=0, help_text='Počet žolíků za celou hru (0-3)', verbose_name='Počet žolíků'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Název kvízu'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=6, unique=True, verbose_name='Kód pro připojení'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Konec sezení'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='Hash pro URL'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Učitel'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quiz.quiz', verbose_name='Kvíz'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Začátek sezení'),
        ),
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.answer', verbose_name='Odpověď'),
        ),
        migrations.AlterField(
            model_name='response',
            name='answered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Odpověděl v'),
        ),
        migrations.AlterField(
            model_name='response',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Správně'),
        ),
        migrations.AlterField(
            model_name='response',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.participant', verbose_name='Účastník'),
        ),
        migrations.AlterField(
            model_name='response',
            name='question_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.questionrun', verbose_name='Běh otázky'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_ms',
            field=models.PositiveIntegerField(default=0, help_text='Čas od začátku otázky v milisekundách', verbose_name='Čas reakce (ms)'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Správně'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Otázka'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.answer', verbose_name='Vybraná odpověď'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('session', 'display_name')},
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('question_run', 'participant')},
        ),
        # Poznámka: unique_together pro studentanswer je komentováno, protože v databázi mohou být duplicitní záznamy
        # migrations.AlterUniqueTogether(
        #     name='studentanswer',
        #     unique_together={('student', 'question')},
        # ),
    ]
