# Generated by Django 6.0 on 2026-01-04 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_change_quiz_to_foreignkey'),
        ('quiz', '0011_add_video_and_document_files'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalmaterial',
            name='document_file',
            field=models.ForeignKey(blank=True, help_text="Nahraný dokument (pouze pro typ 'Dokument')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educational_materials_document', to='wagtaildocs.document', verbose_name='Dokument soubor'),
        ),
        migrations.AddField(
            model_name='educationalmaterial',
            name='video_file',
            field=models.ForeignKey(blank=True, help_text="Nahrané video (pouze pro typ 'Video')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educational_materials_video', to='wagtaildocs.document', verbose_name='Video soubor'),
        ),
        migrations.AlterField(
            model_name='educationalmaterial',
            name='related_quiz',
            field=models.ForeignKey(blank=True, help_text='Kvíz, ke kterému se materiál vztahuje (volitelné)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educational_materials', to='quiz.quiz', verbose_name='Související kvíz'),
        ),
    ]
